sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t ajayonline4u/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true ajayonline4u/docker-react npm run test